version: '3'

services:
  node:
    image: node:18-alpine3.16
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "8080:8080"
    volumes:
      - ../:/src
    working_dir: /src
    depends_on:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:14
    container_name: nokogiri-db-ne-t
    volumes:
      - db-data:/var/lib/postgresql/nokogiri_development/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

ngrok:
  container_name: ngrok
  image: wernight/ngrok:latest
  ports:
    - ${NGROK_PORT:-4040}:4040
  environment:
    NGROK_PORT: app:8080

volumes:
  db-data:
